# Generated by Django 3.0.1 on 2021-01-17 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_phone_number', models.CharField(max_length=20, null=True)),
                ('default_country', models.CharField(max_length=40, null=True)),
                ('default_pdefault_ostcode', models.CharField(blank=True, max_length=20, null=True)),
                ('default_town_or_city', models.CharField(max_length=40, null=True)),
                ('default_street_address1', models.CharField(max_length=80, null=True)),
                ('default_street_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('cdefault_ounty', models.CharField(blank=True, max_length=80, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
