# Generated by Django 3.0.1 on 2021-01-24 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='cdefault_ounty',
            new_name='default_county',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_pdefault_ostcode',
            new_name='default_postcode',
        ),
    ]
