# Generated by Django 3.0.1 on 2020-07-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='friendly_name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
